Improved errors thrown when parsing filters (#49)
# Description

Errors thrown by Koncorde when it parses filters have useful and descriptive messages for humans, but not so much for developpers trying to handle them efficiently.

This PR brings an overhaul of how Koncorde's filter parser handles errors, with the following improvements:
* errors thrown by Koncorde are now `KoncordeParseError` errors (extending the plain `Error` class)
* errors thrown by Koncorde when parsing filters now have a `keyword` property, explaining what keyword caused the error
* errors thrown by Koncorde when parsing filtrers now have a `path` property, giving the full path of errors, which is useful when dealing with complex filters with a composition of `or` and `and` operands
* errors messages generated when parsing filters now are standardized, they all are like this: `"<path>": <message>`. That way, users can easily know where their errors are

Example:

```js
const { Koncorde } = require('koncorde');

const k = new Koncorde();

k.validate({ or: [ { and: [ { exists: {} } ] } ] });
/* 
Throws this error:

KoncordeParseError: "or.and.exists": expected object to have exactly 1 property, got 0
    at isObject (/home/scottinet/git/koncorde/lib/transform/standardize.js:787:13)
    at Standardizer.exists (/home/scottinet/git/koncorde/lib/transform/standardize.js:125:5)
    at Standardizer.standardize (/home/scottinet/git/koncorde/lib/transform/standardize.js:92:29)
    at /home/scottinet/git/koncorde/lib/transform/standardize.js:722:22
    at Array.map (<anonymous>)
    at Standardizer._standardizeFilterArray (/home/scottinet/git/koncorde/lib/transform/standardize.js:722:8)
    at Standardizer.and (/home/scottinet/git/koncorde/lib/transform/standardize.js:584:17)
    at Standardizer.standardize (/home/scottinet/git/koncorde/lib/transform/standardize.js:92:29) {
  keyword: 'exists',
  path: 'or.and.exists'
*/
```